[package]

name = "ink_rust"
version = "0.0.1"
authors = [ "Nathan Jent <nathanjent@nathanjent.com>" ]

[[bin]]

name = "ink_rust"

[dev-dependencies]
serde = "0.7.9"


[build-dependencies]
serde_codegen = "0.7.11"

[dependencies]
conrod = "0.36.1"
piston2d-graphics = "0.16.0"
find_folder = "0.3.0"
piston_window = "0.48.0"
rand = "0.3.13"
lyon = "0.1.1"
xml5ever = "0.1.3"
encoding = "0.2"
cssparser = "0.5.6"
