[package]

name = "ink_rust"
version = "0.0.1"
authors = [ "Nathan Jent <nathanjent@nathanjent.com>" ]

[[bin]]

name = "ink_rust"

[dependencies]
conrod = "0.38.*"
piston2d-graphics = "0.17.*"
find_folder = "0.3.*"
piston_window = "0.51.*"
rand = "0.3.*"
lyon = "0.1.*"
xml5ever = "0.1.*"
encoding = "0.2"
cssparser = "0.5.*"
